[package]
name = "Seam"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
seam = "_"

# Mock addresses for testing.
user = "0x1234"
user_0 = "0x2345"
user_1 = "0x3456"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"